=== praveenoruganti/praveenorugantitech-webservice/praveenoruganti-xsd-master/Patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://praveenorugantitech.blogspot.com/Patient"
	xmlns:tns="http://praveenorugantitech.blogspot.com/Patient"
	elementFormDefault="qualified">
	<element name="Patient" type="tns:Patient" />
	<complexType name="Patient">
		<sequence>
			<element name="Name" type="tns:String15Chars" />
			<element name="Age" type="int" />
			<element name="DOB" type="date" />
			<element name="Email" type="string" maxOccurs="unbounded" />
			<element name="Gender" type="tns:Gender" />
			<element name="Phone" type="string" maxOccurs="2" />
			<element name="payment" type="tns:PaymentType" />
		</sequence>
		<attribute name="id" type="tns:ID"></attribute>
	</complexType>
	<complexType name="PaymentType">
		<choice>
			<element name="cash" type="int"></element>
			<element name="insurance" type="tns:Insurance"></element>
		</choice>
	</complexType>
	<complexType name="Insurance">
		<all>
			<element name="provider" type="string" />
			<element name="limit" type="int" />
		</all>
	</complexType>
	<simpleType name="ID">
		<restriction base="int">
			<pattern value="[0-9]" />
		</restriction>
	</simpleType>
	<simpleType name="String15Chars">
		<restriction base="string">
			<maxLength value="15" />
		</restriction>
	</simpleType>
	<simpleType name="Gender">
		<restriction base="string">
			<enumeration value="M" />
			<enumeration value="F" />
		</restriction>
	</simpleType>
</schema>

=== praveenoruganti/praveenorugantitech-webservice/praveenoruganti-xsd-master/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Patient
	xmlns:tns="http://praveenorugantitech.blogspot.com/Patient"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://praveenorugantitech.blogspot.com/Patient Patient.xsd "
	id="1">
	<tns:Name>PraveenOruganti</tns:Name>
	<tns:Age>34</tns:Age>
	<tns:DOB>2001-01-01</tns:DOB>
	<tns:Email>praveenoruganti@gmail.com</tns:Email>
	<tns:Email>orugantipraveen@gmail.com</tns:Email>
	<tns:Gender>M</tns:Gender>
	<tns:Phone>1234567890</tns:Phone>
	<tns:Phone>1234567891</tns:Phone>
	<tns:payment>
		<tns:insurance>
			<tns:provider>HDFC</tns:provider>
			<tns:limit>100000</tns:limit>
		</tns:insurance>
	</tns:payment>
</tns:Patient>
